INSERT INTO `questsort_dbc` VALUES (1,"Epic","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (21,"REUSE - old wailing caverns","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (22,"Seasonal","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (23,"REUSE - old undercity one","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (24,"Herbalism","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (25,"Battlegrounds","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (41,"Day of the Dead","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (61,"Warlock","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (81,"Warrior","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (82,"Shaman","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (101,"Fishing","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (121,"Blacksmithing","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (141,"Paladin","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (161,"Mage","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (162,"Rogue","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (181,"Alchemy","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (182,"Leatherworking","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (201,"Engineering","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (221,"Treasure Map","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (241,"Tournament","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (261,"Hunter","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (262,"Priest","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (263,"Druid","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (264,"Tailoring","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (284,"Special","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (304,"Cooking","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (324,"First Aid","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (344,"Legendary","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (364,"Darkmoon Faire","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (365,"Ahn\'Qiraj War","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (366,"Lunar Festival","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (367,"Reputation","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (368,"Invasion","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (369,"Midsummer","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (370,"Brewfest","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (371,"Inscription","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (372,"Death Knight","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (373,"Jewelcrafting","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (374,"Noblegarden","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (375,"Pilgrim\'s Bounty","","","","","","","","","","","","","","","",16712190); 
INSERT INTO `questsort_dbc` VALUES (376,"Love is in the Air","","","","","","","","","","","","","","","",16712190); 
